"""全局配置

集中管理所有配置项，支持环境变量覆盖。
统一导出所有配置，保持向后兼容。
"""

# 基础配置
from .base import (
    PROJECT_ROOT,
    DATA_DIR,
    RAW_DATA_DIR,
    PROCESSED_DATA_DIR,
    MOCK_DATA_DIR,
    DB_DIR,
    REPORTS_DIR,
    OLLAMA_URL,
    OLLAMA_TIMEOUT,
    MODELS,
    VERSION,
    APP_NAME,
    APP_ICON,
    DATA_VERSION_CONFIG,
    DATA_LINEAGE_CONFIG,
)

# ESG配置
from .esg import (
    ESG_DIMENSIONS,
    ESG_DIMENSION_NAMES,
    ESG_COLORS,
    ESG_ICONS,
    DEFAULT_SCORE,
    GAP_THRESHOLD_HIGH,
    GAP_THRESHOLD_MEDIUM,
    AHP_CONSISTENCY_THRESHOLD,
    CONFIDENCE_THRESHOLD_HIGH,
    CONFIDENCE_THRESHOLD_MEDIUM,
    AHP_RI_TABLE,
    AHP_SCALE_LABELS,
    DATA_QUALITY_THRESHOLDS,
    DEFAULT_MATERIALITY_SCORES,
    BUSINESS_UNITS,
    TOPIC_BUSINESS_MAP,
    BUSINESS_UNIT_DESCRIPTIONS,
    NEW_ENERGY_SPECIFIC_METRICS,
)

# 标准配置
from .standards import (
    REQUIREMENT_MANDATORY,
    REQUIREMENT_RECOMMENDED,
    ISSB_S1_CLAUSES,
    ISSB_S2_CLAUSES,
    GRI_STANDARDS_CLAUSES,
    DISCLOSURE_STANDARDS,
    COMPLIANCE_STATUS_COMPLIANT,
    COMPLIANCE_STATUS_NON_COMPLIANT,
    COMPLIANCE_STATUS_PARTIAL,
)

# UI配置
from .ui import (
    ANALYSIS_YEARS,
    BENCHMARK_COMPANIES,
    EVALUATION_PERSPECTIVES,
    COMMUNICATION_CALENDAR,
)

__all__ = [
    # base
    "PROJECT_ROOT",
    "DATA_DIR",
    "RAW_DATA_DIR",
    "PROCESSED_DATA_DIR",
    "MOCK_DATA_DIR",
    "DB_DIR",
    "REPORTS_DIR",
    "OLLAMA_URL",
    "OLLAMA_TIMEOUT",
    "MODELS",
    "VERSION",
    "APP_NAME",
    "APP_ICON",
    "DATA_VERSION_CONFIG",
    "DATA_LINEAGE_CONFIG",
    # esg
    "ESG_DIMENSIONS",
    "ESG_DIMENSION_NAMES",
    "ESG_COLORS",
    "ESG_ICONS",
    "DEFAULT_SCORE",
    "GAP_THRESHOLD_HIGH",
    "GAP_THRESHOLD_MEDIUM",
    "AHP_CONSISTENCY_THRESHOLD",
    "CONFIDENCE_THRESHOLD_HIGH",
    "CONFIDENCE_THRESHOLD_MEDIUM",
    "AHP_RI_TABLE",
    "AHP_SCALE_LABELS",
    "DATA_QUALITY_THRESHOLDS",
    "DEFAULT_MATERIALITY_SCORES",
    "BUSINESS_UNITS",
    "TOPIC_BUSINESS_MAP",
    "BUSINESS_UNIT_DESCRIPTIONS",
    "NEW_ENERGY_SPECIFIC_METRICS",
    # standards
    "REQUIREMENT_MANDATORY",
    "REQUIREMENT_RECOMMENDED",
    "ISSB_S1_CLAUSES",
    "ISSB_S2_CLAUSES",
    "GRI_STANDARDS_CLAUSES",
    "DISCLOSURE_STANDARDS",
    "COMPLIANCE_STATUS_COMPLIANT",
    "COMPLIANCE_STATUS_NON_COMPLIANT",
    "COMPLIANCE_STATUS_PARTIAL",
    # ui
    "ANALYSIS_YEARS",
    "BENCHMARK_COMPANIES",
    "EVALUATION_PERSPECTIVES",
    "COMMUNICATION_CALENDAR",
]
