"""全局配置

集中管理所有配置项，支持环境变量覆盖。
统一导出所有配置，保持向后兼容。
"""

# 基础配置
from .base import (
    ANALYSIS_YEARS,
    APP_ICON,
    APP_NAME,
    DATA_DIR,
    DATA_LINEAGE_CONFIG,
    DATA_VERSION_CONFIG,
    DB_DIR,
    MOCK_DATA_DIR,
    MODELS,
    OLLAMA_TIMEOUT,
    OLLAMA_URL,
    PROCESSED_DATA_DIR,
    PROJECT_ROOT,
    RAW_DATA_DIR,
    REPORTS_DIR,
    VERSION,
)

# ESG配置
from .esg import (
    AHP_CONSISTENCY_THRESHOLD,
    AHP_RI_TABLE,
    AHP_SCALE_LABELS,
    BUSINESS_UNIT_DESCRIPTIONS,
    BUSINESS_UNITS,
    CONFIDENCE_THRESHOLD_HIGH,
    CONFIDENCE_THRESHOLD_MEDIUM,
    DATA_QUALITY_THRESHOLDS,
    DEFAULT_MATERIALITY_SCORES,
    DEFAULT_SCORE,
    ESG_COLORS,
    ESG_DIMENSION_NAMES,
    ESG_DIMENSIONS,
    ESG_ICONS,
    GAP_THRESHOLD_HIGH,
    GAP_THRESHOLD_MEDIUM,
    NEW_ENERGY_SPECIFIC_METRICS,
    TOPIC_BUSINESS_MAP,
)

# 传播策略配置
from .communication import COMMUNICATION_CALENDAR

# 评估配置
from .evaluation import (
    BENCHMARK_COMPANIES,
    EVALUATION_PERSPECTIVES,
)

# 标准配置
from .standards import (
    COMPLIANCE_STATUS_COMPLIANT,
    COMPLIANCE_STATUS_NON_COMPLIANT,
    COMPLIANCE_STATUS_PARTIAL,
    DISCLOSURE_STANDARDS,
    GRI_STANDARDS_CLAUSES,
    ISSB_S1_CLAUSES,
    ISSB_S2_CLAUSES,
    REQUIREMENT_MANDATORY,
    REQUIREMENT_RECOMMENDED,
)

# 可视化配置
from .visualization import (
    CARD_BORDER_RADIUS,
    CARD_PADDING,
    CHART_HEIGHT,
    CHART_THEME,
    CONTENT_MAX_WIDTH,
    ESG_CHART_COLORS,
    PRIORITY_COLORS,
    SIDEBAR_WIDTH,
    STATUS_COLORS,
    WORDCLOUD_COLORS,
)

__all__ = [
    # base
    "PROJECT_ROOT",
    "DATA_DIR",
    "RAW_DATA_DIR",
    "PROCESSED_DATA_DIR",
    "MOCK_DATA_DIR",
    "DB_DIR",
    "REPORTS_DIR",
    "OLLAMA_URL",
    "OLLAMA_TIMEOUT",
    "MODELS",
    "VERSION",
    "APP_NAME",
    "APP_ICON",
    "DATA_VERSION_CONFIG",
    "DATA_LINEAGE_CONFIG",
    "ANALYSIS_YEARS",
    # esg
    "ESG_DIMENSIONS",
    "ESG_DIMENSION_NAMES",
    "ESG_COLORS",
    "ESG_ICONS",
    "DEFAULT_SCORE",
    "GAP_THRESHOLD_HIGH",
    "GAP_THRESHOLD_MEDIUM",
    "AHP_CONSISTENCY_THRESHOLD",
    "CONFIDENCE_THRESHOLD_HIGH",
    "CONFIDENCE_THRESHOLD_MEDIUM",
    "AHP_RI_TABLE",
    "AHP_SCALE_LABELS",
    "DATA_QUALITY_THRESHOLDS",
    "DEFAULT_MATERIALITY_SCORES",
    "BUSINESS_UNITS",
    "TOPIC_BUSINESS_MAP",
    "BUSINESS_UNIT_DESCRIPTIONS",
    "NEW_ENERGY_SPECIFIC_METRICS",
    # communication
    "COMMUNICATION_CALENDAR",
    # evaluation
    "BENCHMARK_COMPANIES",
    "EVALUATION_PERSPECTIVES",
    # standards
    "REQUIREMENT_MANDATORY",
    "REQUIREMENT_RECOMMENDED",
    "ISSB_S1_CLAUSES",
    "ISSB_S2_CLAUSES",
    "GRI_STANDARDS_CLAUSES",
    "DISCLOSURE_STANDARDS",
    "COMPLIANCE_STATUS_COMPLIANT",
    "COMPLIANCE_STATUS_NON_COMPLIANT",
    "COMPLIANCE_STATUS_PARTIAL",
    # visualization
    "ESG_CHART_COLORS",
    "PRIORITY_COLORS",
    "STATUS_COLORS",
    "CHART_THEME",
    "CHART_HEIGHT",
    "WORDCLOUD_COLORS",
    "SIDEBAR_WIDTH",
    "CONTENT_MAX_WIDTH",
    "CARD_BORDER_RADIUS",
    "CARD_PADDING",
]
